### PR TITLE
Home carousel

### PR DESCRIPTION
**Pull request by Um-Brehon**
Looks gooood 👌🏻

### CODE REVIEW

**Comment by LoicBrassart** [comment]
No SM validation

**Comment by Um-Brehon** [comment]
I know, but I am the SM this week and I reviewed it. However it's not my code, it's Jeremy's, I only opened the PR. And since I opened the PR, I can't  review it

**Review by KeerhemFR — APPROVED** [review]
Seems okay to me

**Review by Hacene010 — APPROVED** [review]
Seems ok

**Pull request merged**
