### PR TITLE
I did stuff, see comment

### PR DESCRIPTION
**Pull request by Um-Brehon**
Created Articles for the News Page. Created new Article Pages. Added Links to aforementionned pages to App.jsx. I think that's all?

### CODE REVIEW

**Review by Franck59840 — DISMISSED** [review]
good

**Comment by LoicBrassart** [comment]
Please fix conflicts and reassign

**Review by Franck59840 — APPROVED** [review]
resolve conflict with my teammates

**Review by LoicBrassart — APPROVED** [review]
Saw no Evil

**Pull request merged**
